### ISSUE TITLE
特定周波数で特定NAMEを書き込むと例外発生

### ISSUE THREAD

**Issue by k-ishii1020** [bellx2/x100cmd#21]
## 発生条件
136chで 466.350000 `G1`というネームを書き込むと以下の例外発生

### 切り分け
- 他のCHでも発生する
- NAMEを消すとエラーなし
- `G`だとエラーなし
- `G2`でもエラー発生
- `G21`だとエラーなし
- 465.350000　だとエラーなし

エラー共有コメント
https://radio-network.jp/djx100-unofficial-memory-writer/#comment-9

以上よろしくお願いいたします。
```
135[OK]: 466.350000 G
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
github.com/bellx2/x100cmd/djx100.MakeChData({0xc3b236?, 0x51?}, {0x407d25999999999a, 0x0, 0x0, 0x0, {0xc0000c6151, 0x2}, 0x0, 0x0, ...})
        /Users/runner/work/x100cmd/x100cmd/djx100/djx100.go:338 +0x8d1
github.com/bellx2/x100cmd/cmd.glob..func15(0xe10300?, {0xc00010d650?, 0x3?, 0x4?})
        /Users/runner/work/x100cmd/x100cmd/cmd/import.go:203 +0xc0a
github.com/spf13/cobra.(*Command).execute(0xe10300, {0xc000050340, 0x3, 0x4})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xe10e80)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/bellx2/x100cmd/cmd.Execute()
        /Users/runner/work/x100cmd/x100cmd/cmd/root.go:19 +0x25
main.main()
        /Users/runner/work/x100cmd/x100cmd/main.go:10 +0x17
```

**Comment by bellx2** [comment]
➜ x100cmd write 129 -f 466.35 -n G2 
panic: runtime error: index out of range [2] with length 2

MakeChDataでNAMEが2byteの時にindexを超えている

**Comment by bellx2** [comment]
v1.3.10で修正
- ch名が2byteのとき修正
- bankもコードが同じなので修正

**Comment by k-ishii1020** [comment]
ありがとうございます！
